### ISSUE TITLE
Using embedded <audio> instead of microphone

### ISSUE THREAD

**Issue by 5PK** [philnash/react-web-audio#1]
Hey Phil, love this app. I'm attempting to use this to create a 3D audio analyser. However I'm using an embedded piece of audio instead the microphone. I'm having trouble passing the mediaStream to the Analyser and I was wondering if you could help me. 

my modified code in App.js is attached.

```jsx
import React, { Component } from "react";
  import AudioAnalyser from "./audioAnalyser";

import song from './Teehee.mp3';
class Audio extends Component {
  constructor(props) {
    super(props);
    this.state = {        
        audio : null
    };
    this.audioEle = document.getElementById('audio-element');
    this.songName = 'Blues in A';
    this.audioStatus = 'PAUSED';
    this.toggleMusic = this.toggleMusic.bind(this);
  }
  async startMusic() {   
    var mediaStream = this.audioEle.captureStream();
    console.log(mediaStream);
    this.setState({ mediaStream });
  }
  stopMusic() {
    this.state.audio.getTracks().forEach(track => track.stop());
    this.setState({ audio: null }); 
  }
  toggleMusic() {
    if (this.state.audio) {
      this.stopMusic();
    } else {
      this.startMusic();
    }
  }
  render() {
    return (
      <div className="AudioPlayer">        
        <audio id="audio-element" preload="true" src={`${song}`} crossorigin="anonymous" ></audio>
        <div className="controls">
          <button onClick={this.toggleMusic}>
           {this.state.audio ? 'Pause' : 'Play'}
          </button>
        </div>
        {this.state.audio ? <AudioAnalyser audio={this.state.audio} /> : ''}
      </div>
    );
  }
}
export default Audio;
```

however I get this error "Cannot read property 'captureStream' of null"

How come the stream I'm capturing is null? Do I need to start the stream somehow?

Thanks for the tutorial, it's brought me really far.

**Comment by philnash** [comment]
This is cool, but your problem is that you are trying to use the `<audio>` element within the constructor, but this is before the component is rendered so it doesn't exist on the page yet.

What you should do is get a handle to the `<audio>` tag using a [ref](https://reactjs.org/docs/refs-and-the-dom.html). I wrote a bit about doing this with a canvas, but it applies to your `<audio>` element too, here: https://philna.sh/blog/2018/09/27/techniques-for-animating-on-the-canvas-in-react/.

**Comment by 5PK** [comment]
Oh of course, you're right. Thanks for the help Phil, I'm new to React. It works as expected now.

**Comment by philnash** [comment]
Glad you got it sorted!
